import { ensureSystemEntity, getSystemEntities, deleteEntity } from "../../db/entities";

const HELP_ENTITY_FACTS: Record<string, string[]> = {
  help: [
    "$view @everyone",
    "is the help system",
    "topics: start, commands, expressions, patterns, facts, bindings, permissions, models, output",
    "use `/view help:<topic>` for details",
    "---",
    "**Hologram** - Collaborative worldbuilding and roleplay",
    "Everything is an **entity** with **facts**.",
    "---",
    "New here? Try `/view help:start`",
  ],
  "help:start": [
    "$view @everyone",
    "is the getting started guide",
    "---",
    "**Setting up a channel:**",
    "1. `/create Aria` - Create an entity",
    "2. `/edit Aria` - Add facts like personality, appearance",
    "3. `/bind channel Aria` - Bind Aria to this channel",
    "4. Chat! Aria responds when @mentioned",
    "---",
    "**Creating a persona:**",
    "1. `/create MyChar` - Create your entity",
    "2. `/edit MyChar` - Add your entity's facts",
    "3. `/bind me MyChar` - Bind yourself to this entity",
    "4. Your messages now come from MyChar's perspective",
    "---",
    "**Tips:**",
    "• Use `/debug` to see current channel state",
    "• Use `/view <entity>` to view any entity",
    "• Control responses with `$if` (`/view help:expressions`)",
  ],
  "help:commands": [
    "$view @everyone",
    "is help for commands",
    "---",
    "**Commands** (10 total)",
    "`/create` - Create entity",
    "`/view` - View entity facts",
    "`/edit` - Edit entity facts",
    "`/delete` - Delete entity",
    "`/transfer` - Transfer entity ownership",
    "`/bind` - Bind channel/user to entity",
    "`/unbind` - Remove entity binding",
    "`/debug` - Channel state and debug",
    "`/trigger` - Manually trigger an entity",
    "`/forget` - Forget history before now",
    "---",
    "**Debug subcommands:**",
    "`/debug status` - Channel state (default)",
    "`/debug prompt [entity]` - Show system prompt",
    "`/debug history [entity]` - Show message history",
    "---",
    "**Examples:**",
    "`/create Aria` - Create entity",
    "`/view Aria` - View facts",
    "`/bind channel Aria` - Bind to channel",
  ],
  "help:expressions": [
    "$view @everyone",
    "is help for $if expressions and response control",
    "---",
    "**Syntax:** `$if <expr>: <fact or directive>`",
    "Expressions are JavaScript. Strings need quotes: `\"hello\"` not `hello`",
    "---",
    "**Directives:**",
    "• `$respond` / `$respond false` - control response",
    "• `$retry <ms>` - re-evaluate after delay",
    "• `$stream` / `$model` / `$context` / `$strip` - see `/view help:output`",
    "---",
    "**Operators:**",
    "`&&` `||` `!` `==` `!=` `<` `>` `<=` `>=`",
    "`+` `-` `*` `/` `%` `? :`",
    "---",
    "**Context variables:**",
    "• `mentioned`, `replied`, `is_forward` - message flags",
    "• `is_self` - message from this entity's webhook",
    "• `content`, `author` - message data",
    "• `name` - this entity's name",
    "• `chars` - array of all bound character names",
    "• `response_ms` - ms since last response",
    "• `retry_ms` - ms since trigger (for $retry)",
    "• `idle_ms` - ms since any message in channel",
    "---",
    "**Time:** `time.hour`, `time.is_day`, `time.is_night`",
    "**Self:** `self.key` from `key: value` facts",
    "**Channel:** `channel.id`, `channel.name`, `channel.description`, `channel.mention`",
    "**Server:** `server.id`, `server.name`, `server.description`",
    "---",
    "**Functions:**",
    "• `random()` - float 0-1",
    "• `random(n)` - int 1-n",
    "• `has_fact(\"pattern\")` - regex match",
    "• `roll(\"2d6+3\")` - dice roll (roll20 syntax: kh, kl, dh, dl, !, >=)",
    "• `mentioned_in_dialogue(name)` - name in dialogue (not XML tags)",
    "• `messages(n, fmt, filter)` - last n messages (filter: \"$user\", \"$char\", or name)",
    "• `duration(ms)` - human-readable duration",
    "• `date_str(offset?)` - date string (e.g. \"Thu Jan 30 2026\")",
    "• `time_str(offset?)` - time string (e.g. \"6:00 PM\")",
    "• `isodate(offset?)` / `isotime(offset?)` - ISO format",
    "• `weekday(offset?)` - day name (e.g. \"Thursday\")",
    "---",
    "`content` and `author` are aliases for `messages(1, \"%m\")` and `messages(1, \"%a\")`",
    "---",
    "**Additional variables:** `group` (all bound chars), `name` (entity name)",
    "---",
    "See `/view help:patterns` for common examples",
  ],
  "help:patterns": [
    "$view @everyone",
    "is help for common $if patterns",
    "---",
    "**Recommended defaults:**",
    '`$if chars.length === 1 && (mentioned || replied): $respond`',
    '`$if content.toLowerCase().match("\\\\b" + name + "\\\\b"): $respond`',
    "---",
    "**Response triggers:**",
    "`$respond` - always respond",
    "`$respond false` - never respond",
    "`$if mentioned: $respond` - only @mentions",
    "`$if mentioned || replied: $respond` - mentions or replies",
    "---",
    "**Rate limiting:**",
    "`$if response_ms > 30000: $respond` - 30s cooldown",
    "`$if response_ms > 60000 || mentioned: $respond` - 1min unless mentioned",
    "---",
    "**Randomness:**",
    "`$if random() < 0.1: $respond` - 10% chance",
    "`$if random() < 0.3 && !mentioned: $respond` - 30% lurk",
    "---",
    "**Time-based:**",
    "`$if time.is_night: becomes more mysterious`",
    "`$if time.hour >= 22 || time.hour < 6: $respond false`",
    "---",
    "**Multi-character:**",
    "`$if chars.length === 1: $respond` - only if alone",
    "`$if chars.length > 1 && mentioned: $respond` - need mention in group",
    "---",
    "**Name in dialogue:**",
    '`$if mentioned_in_dialogue(name) && !is_self: $respond`',
    "Responds when name appears in chat (not from self)",
    "---",
    "**Delayed response:**",
    "`$retry 5000` - wait 5s then re-evaluate",
    "`$if retry_ms > 10000: $respond` - after 10s delay",
  ],
  "help:facts": [
    "$view @everyone",
    "is help for facts",
    "---",
    "**Facts** - Define entities",
    "Facts are freeform text.",
    "---",
    "**Two styles:**",
    "• Discrete facts (easy to update individually)",
    "• Single prose description (SillyTavern style)",
    "Both work fine!",
    "---",
    "**Macros:**",
    "• `{{entity:12}}` - entity reference (expands to name)",
    "• `{{char}}` - current entity's name",
    "• `{{user}}` - literal \"user\"",
    "• `{{expression}}` - any valid expression (e.g. `{{channel.name}}`, `{{self.health}}`)",
    "• `{{date}}` `{{time}}` `{{weekday}}` `{{isodate}}` `{{isotime}}` - date/time",
    "• `{{group}}` `{{model}}` `{{maxPrompt}}` - context info",
    "• `{{random: A,B,C}}` - random from list",
    "• `{{roll: 2d6+3}}` - dice roll (roll20 syntax)",
    "• `{{newline}}` `{{space}}` `{{noop}}` `{{trim}}` - formatting",
    "• `{{lastMessage}}` `{{lastUserMessage}}` `{{lastCharMessage}}` - history",
    "• `{{idle_duration}}` - human-readable idle time",
    "• `$if condition: $respond` - response control",
    "---",
    "**Permissions:** See `/view help:permissions`",
  ],
  "help:bindings": [
    "$view @everyone",
    "is help for bindings",
    "---",
    "**Bindings** - Connect Discord to entities",
    "---",
    "`/bind channel <entity>` - Add entity to channel",
    "`/unbind channel <entity>` - Remove entity",
    "`/bind me <entity>` - Speak as entity",
    "---",
    "**Multiple entities:** Bind several entities to one channel. Each evaluates `$respond` independently.",
    "---",
    "**Scopes:** channel (default), guild, global",
  ],
  "help:permissions": [
    "$view @everyone",
    "is help for entity permissions",
    "---",
    "**Ownership** - Each entity has an owner",
    "• Creator owns by default",
    "• Owner always has full access",
    "• `/transfer <entity> <user>` - Transfer ownership",
    "---",
    "**Blacklist** - Block specific users",
    "• `$blacklist username` - Block by username",
    "• `$blacklist 123456789012345678` - Block by Discord ID or role ID",
    "• `$blacklist user1, 123456789, user2` - Mixed",
    "• Blocked users cannot view, edit, or receive responses",
    "• Owner is never blocked",
    "---",
    "**LLM Lock** - Prevent AI modifications",
    "• `$locked` - Lock entire entity",
    "• `$locked has silver hair` - Lock specific fact",
    "AI can still see locked facts, but cannot modify them.",
    "---",
    "**User Access** - Control who can edit/view/use",
    "• `$edit @everyone` - Anyone can edit",
    "• `$edit alice, bob` - Usernames (case-insensitive)",
    "• `$edit 123456789012345678` - Discord user or role IDs",
    "• `$view @everyone` - Anyone can view",
    "• `$view alice, 123456789` - Mixed usernames and IDs",
    "• `$use @everyone` - Anyone can trigger responses",
    "• `$use alice, 123456789` - Restrict who can trigger",
    "---",
    "**Defaults:**",
    "• Blacklist: empty (nobody blocked)",
    "• Edit: owner only",
    "• View: owner only",
    "• Use: everyone (no restriction)",
    "• LLM: not locked",
    "---",
    "All permission directives accept usernames, Discord user IDs, and role IDs.",
  ],
  "help:models": [
    "$view @everyone",
    "is help for models",
    "---",
    "**Models** - `provider:model` format",
    "---",
    "• `google:gemini-3-flash-preview`",
    "• `google:gemini-2.5-flash-lite-preview-06-2025`",
    "• `anthropic:claude-sonnet-4-20250514`",
    "• `openai:gpt-4o`",
  ],
  "help:output": [
    "$view @everyone",
    "is help for output directives",
    "---",
    "**Output directives** control how the LLM generates and delivers responses.",
    "---",
    "**`$model provider:model`** - Override the LLM model",
    '`$model google:gemini-2.0-flash`',
    '`$if mentioned: $model openai:gpt-4o`',
    "See `/view help:models` for available models.",
    "---",
    "**`$stream`** - Stream responses progressively",
    "`$stream` - new message per line",
    '`$stream full` - single message, edited as it streams',
    '`$stream "delimiter"` - split on custom text',
    "---",
    "**`$context <expr>`** - Control message history filtering",
    "`$context 8k` - up to 8,000 characters",
    "`$context chars < 16000` - same as `$context 16k`",
    "`$context (chars < 4000 || count < 20) && age_h < 12` - complex filter",
    "Vars: `chars`, `count`, `age_h`, `age_m`, `age_s`, `age`",
    "---",
    '**`$strip "<pattern>"`** - Strip strings from message history',
    '`$strip "</blockquote>"` - strip this pattern',
    '`$strip "</blockquote>" "<br>"` - strip multiple',
    "`$strip` - explicitly disable stripping",
    "Default: strips `</blockquote>` on gemini-2.5-flash-preview only.",
    "---",
    "**`$freeform`** - Allow natural multi-character prose",
    "Disables per-character message splitting in multi-char channels.",
  ],
};

export function ensureHelpEntities(): void {
  for (const [name, facts] of Object.entries(HELP_ENTITY_FACTS)) {
    ensureSystemEntity(name, facts);
  }

  // Delete stale system entities no longer in the help map
  const validNames = new Set(Object.keys(HELP_ENTITY_FACTS));
  for (const entity of getSystemEntities()) {
    if (!validNames.has(entity.name)) {
      deleteEntity(entity.id);
    }
  }
}
